<!DOCTYPE html> <!--menandakan html versi 5 (tipe)-->
<html lang="en"> <!--html : untuk membuat dokumen html, lang : untuk menyatakan bahasa halaman web-->
<?php include "head.inc" ?> <!--menyisipkan file head.inc-->

<body>
    <?php include "navbar.inc"; ?><!--menyisipkan file navbar.inc-->
    <div class="content"> <!--div sebagai kontainer dengan class content-->
        <h1 class="center-text">Welcome To Symposium Hardware</h1><!--tag h1 untuk mencetak tulisan bold dan setara dengan 24pt-->
    </div>
    <?php include "footer.inc"; ?> <!---menyisipkan file footer.inc-->
</body>

</html>